version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"